---

- name: Roll out (static) dotfiles to {{ dotfiles_destination }}
  copy:
    src: "{{ item }}"
    dest: "{{ dotfiles_destination }}/{{ item }}"
    backup: yes
  loop: "{{ dotfiles }}"

- name: Roll out dotfile templates to {{ dotfiles_destination }}
  template:
    src: .gitconfig.j2
    dest: "{{ dotfiles_destination }}/.gitconfig"

- name: Add umask fix for WSL
  blockinfile:
    path: ~/.profile
    block: |
      # Note: Bash on Windows does not currently apply umask properly.
      if [[ "$(umask)" = "0000" ]]; then
         umask 0022
      fi
  when: '"Microsoft" in ansible_kernel'
