---

- name: Roll out (static) dotfiles to {{ dotfiles_destination }}
  copy:
    src: "{{ item }}"
    dest: "{{ dotfiles_destination }}/{{ item }}"
    backup: yes
  loop: "{{ dotfiles }}"

- name: Roll out dotfile templates to {{ dotfiles_destination }}
  template:
    src: .gitconfig.j2
    dest: "{{ dotfiles_destination }}/.gitconfig"

