---

# Regular expression removes the .j2 ending of templates
- name: Roll out dotfiles to {{ dotfiles_destination }}
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ dotfiles_destination }}/{{ item | regex_replace('^(.*)(.j2)$', '\\1') }}"
    backup: yes
  loop: "{{ dotfiles }}"
