---

# Regular expression removes the .j2 ending of templates
- name: Roll out dotfiles to {{ dotfiles_destination }}
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ dotfiles_destination }}/{{ item | regex_replace('^(.*)(.j2)$', '\\1') }}"
    backup: yes
  loop: "{{ dotfiles }}"

- name: Disable bell
  ansible.builtin.blockinfile:
    path: "{{ dotfiles_destination }}/.bashrc"
    block: |
      # Disable bell
      bind 'set bell-style none'
    state: present
