---

- name: Check for sudo permissions
  command: sudo -n -l
  register: sudo_permission
  become: yes
  failed_when: sudo_permission.rc > 1
  changed_when: false
  args:
    warn: false

- name: Install useful applications and tools for RedHat-based systems
  yum:
    name:
      - vim
      - ansible-lint
      - yamllint
    state: present
  become: yes
  when:
    - sudo_permission.module_stderr is not defined
    - ansible_os_family == "RedHat"

- name: Install useful applications and tools for Debian-based systems
  apt:
    name:
      - vim
      - ansible-lint
      - yamllint
    state: present
  become: yes
  when:
    - sudo_permission.module_stderr is not defined
    - ansible_os_family == "Debian"
