---

- name: Check for sudo permissions
  command: sudo -v
  register: sudo_permission
  failed_when: sudo_permission.rc > 1
  changed_when: false
  args:
    warn: false

- name: Install useful applications and tools, if possible
  yum:
    name:
      - vim
      - ansible-lint
      - yaml-lint
  become: yes
  when: '"Sorry" not in sudo_permission.stderr'

