---

- name: Check for sudo permissions
  ansible.builtin.command: sudo -n -l
  register: sudo_permission
  become: yes
  failed_when: sudo_permission.rc > 1
  changed_when: false
  args:
    warn: false

- name: Info
  ansible.builtin.debug:
    msg: "You do not have sufficient sudo permissions, installing application won't work!"
  when: sudo_permission.module_stderr is defined

- name: Install useful applications and tools for RedHat-based systems
  ansible.builtin.yum:
    name:
      - vim
      - ansible-lint
      - yamllint
    state: present
    update_cache: yes
  become: yes
  when:
    - sudo_permission.module_stderr is not defined
    - ansible_os_family == "RedHat"

- name: Install useful applications and tools for Debian-based systems
  ansible.builtin.apt:
    name:
      - vim
      - ansible-lint
      - yamllint
    state: present
    update_cache: yes
  become: yes
  when:
    - sudo_permission.module_stderr is not defined
    - ansible_os_family == "Debian"
