---

- name: Check for sudo permissions
  ansible.builtin.command: sudo -n -l
  register: sudo_permission
  failed_when: sudo_permission.rc > 1
  changed_when: false
  check_mode: no
  args:
    warn: false

- name: Info
  ansible.builtin.fail:
    msg:
      - Installing applications won't work!
      - You do not have sufficient sudo permissions, a password is required.
      - Try running the playbook with '-K' (--ask-become-pass) and provide the sudo password.
      - For skipping the tool installation, run the playbook with '--skip-tags tools'
  when:
    - sudo_permission.stderr is defined
    - '"password is required" in sudo_permission.stderr'

- name: Install useful applications and tools for RedHat-based systems
  ansible.builtin.yum:
    name:
      - vim
      - ansible-lint
      - yamllint
    state: present
    update_cache: yes
  become: yes
  when:
    - ansible_os_family == "RedHat"

- name: Install useful applications and tools for Debian-based systems
  ansible.builtin.apt:
    name:
      - vim
      - ansible-lint
      - yamllint
    state: present
    update_cache: yes
  become: yes
  when:
    - ansible_os_family == "Debian"
