---

- name: Create SSH keypair for User {{ ansible_user_id }}
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"

# As the playbook is meant to run on localhost, it utilizes lookup
# This will not work on remote hosts and when testing with molecule
- name: Output local SSH public key
  ansible.builtin.debug:
    msg: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
