---

- name: Check for existing SSH keypair
  stat:
    path: ~/.ssh/id_rsa
  register: ssh_private_key_presence
  
- name: Create SSH keypair
  openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa
    size: 4096
    comment: "{{ ansible_env.USER }}@{{ ansible_hostname }}"
  when: not ssh_private_key_presence

- name: Output SSH public key, when copying, be careful not to copy the quotation marks
  debug:
    msg: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
